server.port=8888
spring.application.name=config-server
spring.cloud.config.server.git.uri=https://github.com/Yesaswi16/flowers-config-repo.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
logging.level.org.springframework.cloud.config=DEBUG